### ISSUE TITLE
uncaught errors when adding pseudo-positioner

### ISSUE THREAD

**Issue by prjemian** [bluesky/hklpy#48]
When testing the addition of positioners to a Diffractometer object, it was discovered that there are uncaught errors when adding a pseudo-positioner.

```
============================= test session starts ==============================
platform linux -- Python 3.7.7, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir: /tmp/pytest-of-prjemian/pytest-13/test_extra_pseudo_ok0
collected 0 items / 1 error

==================================== ERRORS ====================================
___________________ ERROR collecting test_extra_pseudo_ok.py ___________________
/home/prjemian/Apps/anaconda/envs/hkl/lib/python3.7/site-packages/ophyd/device.py:223: in __get__
    return instance._signals[self.attr]
E   KeyError: 'extra'

During handling of the above exception, another exception occurred:
...
```

* [stdout.txt](https://github.com/bluesky/hklpy/files/5431970/stdout.txt)
* [test_extra_pseudo_ok.py.txt](https://github.com/bluesky/hklpy/files/5431974/test_extra_pseudo_ok.py.txt)

**Comment by prjemian** [comment]
Most recent run:

```
(hkl) prjemian@poof ~/.../Bluesky/hklpy $ pytest hkl/tests/test_extra_motor.py 
=================================================================================== test session starts ====================================================================================
platform linux -- Python 3.7.7, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/prjemian/Documents/projects/Bluesky/hklpy
collected 6 items                                                                                                                                                                          

hkl/tests/test_extra_motor.py .....F                                                                                                                                                 [100%]

========================================================================================= FAILURES =========================================================================================
_________________________________________________________________________________ test_fourc_extra_pseudo __________________________________________________________________________________

    def test_fourc_extra_pseudo():
        class FourcSub(Fourc):
            _pseudo = ['h', 'k', 'l', ]
            p_extra = Cpt(PseudoSingle, '')
        fourc = FourcSub('', name="fourc")
        # FIXME: uncaught TypeError
        # TypeError: tuple indices must be integers or slices, not NoneType
        # with pytest.raises(Exception) as exinfo:
        #     fourc = FourcSub('', name="fourc")
        # assert "tuple indices must be integers or slices" in str(exinfo.value)
        assert fourc.position == (0, 0, 0)
>       assert fourc.p_extra.get() == 0

hkl/tests/test_extra_motor.py:114: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../../Apps/anaconda/envs/hkl/lib/python3.7/site-packages/ophyd/device.py:1361: in get
    values[attr] = signal.get(**kwargs)
../../../../Apps/anaconda/envs/hkl/lib/python3.7/site-packages/ophyd/signal.py:1780: in get
    self._readback = getattr(self.base, self.attr)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = PseudoSingle(prefix='', name='fourc_p_extra', parent='fourc', settle_time=0.0, timeout=None, egu='', limits=(0, 0), source='computed', read_attrs=['readback', 'setpoint'], configuration_attrs=[], idx=None)

    @property
    def position(self):
        '''The current position of the motor in its engineering units
    
        Returns
        -------
        position
        '''
>       return self._parent.position[self._idx]
E       TypeError: tuple indices must be integers or slices, not NoneType

../../../../Apps/anaconda/envs/hkl/lib/python3.7/site-packages/ophyd/pseudopos.py:125: TypeError
------------------------------------------------------------------------------------ Captured log call -------------------------------------------------------------------------------------
ERROR    ophyd.objects:ophydobj.py:467 Subscription readback callback exception (FourcSub(prefix='', name='fourc', settle_time=0.0, timeout=None, egu='', limits=(0, 0), source='computed', read_attrs=['h', 'h.readback', 'h.setpoint', 'k', 'k.readback', 'k.setpoint', 'l', 'l.readback', 'l.setpoint', 'omega', 'chi', 'phi', 'tth'], configuration_attrs=['energy', 'UB', 'h', 'k', 'l', 'p_extra'], concurrent=True))
Traceback (most recent call last):
  File "/home/prjemian/Apps/anaconda/envs/hkl/lib/python3.7/site-packages/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/home/prjemian/Apps/anaconda/envs/hkl/lib/python3.7/site-packages/ophyd/device.py", line 1620, in wrapped
    ret = func(self, *args, **kwargs)
  File "/home/prjemian/Apps/anaconda/envs/hkl/lib/python3.7/site-packages/ophyd/pseudopos.py", line 94, in _sub_proxy_readback
    value = value[self._idx]
TypeError: tuple indices must be integers or slices, not NoneType
================================================================================= short test summary info ==================================================================================
FAILED hkl/tests/test_extra_motor.py::test_fourc_extra_pseudo - TypeError: tuple indices must be integers or slices, not NoneType
=============================================================================== 1 failed, 5 passed in 5.99s ================================================================================
(hkl) prjemian@poof ~/.../Bluesky/hklpy $ 
```

**Comment by prjemian** [comment]
```
(hkl) prjemian@poof ~/.../Bluesky/hklpy $ pytest hkl/tests/test_extra_motor.py 
=================================================================================== test session starts ====================================================================================
platform linux -- Python 3.7.7, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/prjemian/Documents/projects/Bluesky/hklpy
collected 6 items                                                                                                                                                                          

hkl/tests/test_extra_motor.py .....F                                                                                                                                                 [100%]

========================================================================================= FAILURES =========================================================================================
_________________________________________________________________________________ test_fourc_extra_pseudo __________________________________________________________________________________

    def test_fourc_extra_pseudo():
        class FourcSub(Fourc):
            _pseudo = ['h', 'k', 'l', ]
            p_extra = Cpt(PseudoSingle, '')
        fourc = FourcSub('', name="fourc")
        # FIXME: uncaught TypeError
        # TypeError: tuple indices must be integers or slices, not NoneType
        # with pytest.raises(Exception) as exinfo:
        #     fourc = FourcSub('', name="fourc")
        # assert "tuple indices must be integers or slices" in str(exinfo.value)
        assert fourc.position == (0, 0, 0)
        assert hasattr(fourc.p_extra, "_idx")
>       assert fourc.p_extra._idx is not None
E       AssertionError: assert None is not None
E        +  where None = PseudoSingle(prefix='', name='fourc_p_extra', parent='fourc', settle_time=0.0, timeout=None, egu='', limits=(0, 0), source='computed', read_attrs=['readback', 'setpoint'], configuration_attrs=[], idx=None)._idx
E        +    where PseudoSingle(prefix='', name='fourc_p_extra', parent='fourc', settle_time=0.0, timeout=None, egu='', limits=(0, 0), source='computed', read_attrs=['readback', 'setpoint'], configuration_attrs=[], idx=None) = FourcSub(prefix='', name='fourc', settle_time=0.0, timeout=None, egu='', limits=(0, 0), source='computed', read_attrs=...point', 'omega', 'chi', 'phi', 'tth'], configuration_attrs=['energy', 'UB', 'h', 'k', 'l', 'p_extra'], concurrent=True).p_extra

hkl/tests/test_extra_motor.py:115: AssertionError
------------------------------------------------------------------------------------ Captured log call -------------------------------------------------------------------------------------
ERROR    ophyd.objects:ophydobj.py:467 Subscription readback callback exception (FourcSub(prefix='', name='fourc', settle_time=0.0, timeout=None, egu='', limits=(0, 0), source='computed', read_attrs=['h', 'h.readback', 'h.setpoint', 'k', 'k.readback', 'k.setpoint', 'l', 'l.readback', 'l.setpoint', 'omega', 'chi', 'phi', 'tth'], configuration_attrs=['energy', 'UB', 'h', 'k', 'l', 'p_extra'], concurrent=True))
Traceback (most recent call last):
  File "/home/prjemian/Apps/anaconda/envs/hkl/lib/python3.7/site-packages/ophyd/ophydobj.py", line 462, in inner
    cb(*args, **kwargs)
  File "/home/prjemian/Apps/anaconda/envs/hkl/lib/python3.7/site-packages/ophyd/device.py", line 1620, in wrapped
    ret = func(self, *args, **kwargs)
  File "/home/prjemian/Apps/anaconda/envs/hkl/lib/python3.7/site-packages/ophyd/pseudopos.py", line 94, in _sub_proxy_readback
    value = value[self._idx]
TypeError: tuple indices must be integers or slices, not NoneType
================================================================================= short test summary info ==================================================================================
FAILED hkl/tests/test_extra_motor.py::test_fourc_extra_pseudo - AssertionError: assert None is not None
=============================================================================== 1 failed, 5 passed in 5.94s ================================================================================
```

**Comment by prjemian** [comment]
@Maksim: How to catch this exception?  Is it actually a problem upstream?

**Comment by prjemian** [comment]
Looks like a problem upstream.  In [ophyd.pseudopos, lines 417-8](https://github.com/bluesky/ophyd/blob/66aa2d921ad9f4f7259864665cb4ec1ad22ceeb9/ophyd/pseudopos.py#L67-L73), the `_idx` is clearly set to `None` with statement that it will be set later:

```
        # The index of this PseudoSingle in the parent PseudoPositioner tuple
        # will be set post-instantiation:
        self._idx = None
        self._parent.subscribe(self._sub_proxy_start, event_type=self.SUB_START)
        self._parent.subscribe(self._sub_proxy_done, event_type=self.SUB_DONE)
        self._parent.subscribe(self._sub_proxy_readback,
                               event_type=self.SUB_READBACK)
```

[Later](https://github.com/bluesky/ophyd/blob/66aa2d921ad9f4f7259864665cb4ec1ad22ceeb9/ophyd/pseudopos.py#L417-L418), it would be set by this code:

```
        for idx, pseudo in enumerate(self._pseudo):
            pseudo._idx = idx
```

but this fails because we are following these [instructions](https://github.com/bluesky/ophyd/blob/66aa2d921ad9f4f7259864665cb4ec1ad22ceeb9/ophyd/pseudopos.py#L491-L493)

```
        The built-in mechanism to override the list of pseudo positioners on a
        PseudoPositioner is to define '_pseudo' on the class-level.  It should
        be a list of attribute names.
```

In our test, we setup a `Fourc` class:  https://github.com/bluesky/hklpy/blob/98eb88c0a05dff7b200b58d36bffe77dbdd155cb/hkl/tests/test_extra_motor.py#L13-L27

then subclass per instructions. https://github.com/bluesky/hklpy/blob/98eb88c0a05dff7b200b58d36bffe77dbdd155cb/hkl/tests/test_extra_motor.py#L104-L106   The `enumerate(self._pseudo)` part misses our additional pseudo-positioner.

Need to refactor to use code that walks through _all_ pseudo-positioners, not just the ones in `_pseudo`, [such as](enumerate(self._pseudo)):

```
            for attr, cpt in cls._sig_attrs.items():
                if issubclass(cpt.cls, PseudoSingle):
                    yield attr, cpt
```

**Comment by prjemian** [comment]
see WIP commit 98eb88c

**Comment by prjemian** [comment]
conclusion: The feature to add additional pseudo positioners in the `ophyd.pseudopos.PseudoPositioner` is broken at this time.  See: https://github.com/bluesky/ophyd/issues/924

**Comment by tacaswell** [comment]
The core of the problem is that the `PseudoSingle` class expects to be able to reach up to its parent to get its current value (rather than storing it internally).  If you have excluded it from the machinery of the parent class to give it a value it (reasonable) does not have a value.  While it is plausible that we should have a better error, I'm not sure what the expected behavior would be.

**Comment by prjemian** [comment]
Here's an additional unit test, but still does not resolve the problem:

```python


def test_fourc_extra_pseudo():
    class FourcSub(Fourc):
        _pseudo = ['h', 'k', 'l', ]
        p_extra = Cpt(PseudoSingle, '')
    fourc = FourcSub('', name="fourc")
    assert fourc.position == (0, 0, 0)
    assert hasattr(fourc.p_extra, "_idx")
    # TODO: this feature is broken in ophyd at this time
    # https://github.com/bluesky/hklpy/issues/48
    # https://github.com/bluesky/ophyd/issues/924
    assert fourc.p_extra._idx is None

    # issue #48
    assert fourc.h.position == 0
    assert fourc.k.position == 0
    assert fourc.l.position == 0
    with pytest.raises(TypeError) as exinfo:
        fourc.p_extra.position
    expected = "tuple indices must be integers or slices, not NoneType"
    assert expected in str(exinfo.value)
```

Since this can't be trapped (without adding convoluted code for this unusual case), pushing this to a later milestone.

**Comment by prjemian** [comment]
This is an upstream problem that cannot be fixed here.
